 
import "./globals.css";
import {Navbar} from "@/components";
import {StateContext} from '@/context/StageContext'




import {  lora } from './font';

 
 
 



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="w-screen " lang="en">
      <body className={lora.className}>
      <StateContext  >
        <Navbar/>

        {children}
        </StateContext  >
        </body>
    </html>
  );
}
